{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sqlite3\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "ship = pd.read_csv('titanic.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [],
   "source": [
    "ship.columns= ship.columns.str.replace(' ','_')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [],
   "source": [
    "ship.columns = ship.columns.str.replace('/','_')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Survived</th>\n",
       "      <th>Pclass</th>\n",
       "      <th>Name</th>\n",
       "      <th>Sex</th>\n",
       "      <th>Age</th>\n",
       "      <th>Siblings_Spouses_Aboard</th>\n",
       "      <th>Parents_Children_Aboard</th>\n",
       "      <th>Fare</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>Mr. Owen Harris Braund</td>\n",
       "      <td>male</td>\n",
       "      <td>22.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>7.2500</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Mrs. John Bradley (Florence Briggs Thayer) Cum...</td>\n",
       "      <td>female</td>\n",
       "      <td>38.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>71.2833</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>Miss. Laina Heikkinen</td>\n",
       "      <td>female</td>\n",
       "      <td>26.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>7.9250</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Mrs. Jacques Heath (Lily May Peel) Futrelle</td>\n",
       "      <td>female</td>\n",
       "      <td>35.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>53.1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>Mr. William Henry Allen</td>\n",
       "      <td>male</td>\n",
       "      <td>35.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>8.0500</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Survived  Pclass                                               Name  \\\n",
       "0         0       3                             Mr. Owen Harris Braund   \n",
       "1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   \n",
       "2         1       3                              Miss. Laina Heikkinen   \n",
       "3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   \n",
       "4         0       3                            Mr. William Henry Allen   \n",
       "\n",
       "      Sex   Age  Siblings_Spouses_Aboard  Parents_Children_Aboard     Fare  \n",
       "0    male  22.0                        1                        0   7.2500  \n",
       "1  female  38.0                        1                        0  71.2833  \n",
       "2  female  26.0                        0                        0   7.9250  \n",
       "3  female  35.0                        1                        0  53.1000  \n",
       "4    male  35.0                        0                        0   8.0500  "
      ]
     },
     "execution_count": 68,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ship.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "metadata": {},
   "outputs": [],
   "source": [
    "ship['Name'] = ship['Name'].str.replace(' ','_')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "metadata": {},
   "outputs": [],
   "source": [
    "ship['Name'] = ship['Name'].str.replace('.',\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 145,
   "metadata": {},
   "outputs": [],
   "source": [
    "ship['Name'] = ship['Name'].str.replace(\"'\",\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 121,
   "metadata": {},
   "outputs": [],
   "source": [
    "ship['Sex'] = ship['Sex'].replace({'male':'0','female':'1'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 146,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Survived</th>\n",
       "      <th>Pclass</th>\n",
       "      <th>Name</th>\n",
       "      <th>Sex</th>\n",
       "      <th>Age</th>\n",
       "      <th>Siblings_Spouses_Aboard</th>\n",
       "      <th>Parents_Children_Aboard</th>\n",
       "      <th>Fare</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>Mr_Owen_Harris_Braund</td>\n",
       "      <td>0</td>\n",
       "      <td>22.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>7.2500</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Mrs_John_Bradley_(Florence_Briggs_Thayer)_Cumings</td>\n",
       "      <td>1</td>\n",
       "      <td>38.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>71.2833</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>Miss_Laina_Heikkinen</td>\n",
       "      <td>1</td>\n",
       "      <td>26.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>7.9250</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Mrs_Jacques_Heath_(Lily_May_Peel)_Futrelle</td>\n",
       "      <td>1</td>\n",
       "      <td>35.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>53.1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>Mr_William_Henry_Allen</td>\n",
       "      <td>0</td>\n",
       "      <td>35.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>8.0500</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Survived  Pclass                                               Name Sex  \\\n",
       "0         0       3                              Mr_Owen_Harris_Braund   0   \n",
       "1         1       1  Mrs_John_Bradley_(Florence_Briggs_Thayer)_Cumings   1   \n",
       "2         1       3                               Miss_Laina_Heikkinen   1   \n",
       "3         1       1         Mrs_Jacques_Heath_(Lily_May_Peel)_Futrelle   1   \n",
       "4         0       3                             Mr_William_Henry_Allen   0   \n",
       "\n",
       "    Age  Siblings_Spouses_Aboard  Parents_Children_Aboard     Fare  \n",
       "0  22.0                        1                        0   7.2500  \n",
       "1  38.0                        1                        0  71.2833  \n",
       "2  26.0                        0                        0   7.9250  \n",
       "3  35.0                        1                        0  53.1000  \n",
       "4  35.0                        0                        0   8.0500  "
      ]
     },
     "execution_count": 146,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ship.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "81"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# What is the longest \n",
    "ship.Name.map(lambda x:\n",
    "             len(x)).max()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [],
   "source": [
    "import psycopg2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 159,
   "metadata": {},
   "outputs": [],
   "source": [
    "conn = psycopg2.connect(dbname= 'vcnlcpsj',\n",
    "                        user='vcnlcpsj',\n",
    "                       password = 'wCVuZq-biifESAFhoRpDIlG2r4eD9fgj',\n",
    "                       host = 'rajje.db.elephantsql.com')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 160,
   "metadata": {},
   "outputs": [],
   "source": [
    "curs = conn.cursor()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 164,
   "metadata": {},
   "outputs": [],
   "source": [
    "curs.execute('SELECT * FROM titanic_table;')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 165,
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[(0, False, 'Mr_Owen_Harris_Braund', False, 22),\n",
       " (1, True, 'Mrs_John_Bradley_(Florence_Briggs_Thayer)_Cumings', True, 38),\n",
       " (2, True, 'Miss_Laina_Heikkinen', True, 26),\n",
       " (3, True, 'Mrs_Jacques_Heath_(Lily_May_Peel)_Futrelle', True, 35),\n",
       " (4, False, 'Mr_William_Henry_Allen', False, 35),\n",
       " (5, False, 'Mr_James_Moran', False, 27),\n",
       " (6, False, 'Mr_Timothy_J_McCarthy', False, 54),\n",
       " (7, False, 'Master_Gosta_Leonard_Palsson', False, 2),\n",
       " (8, True, 'Mrs_Oscar_W_(Elisabeth_Vilhelmina_Berg)_Johnson', True, 27),\n",
       " (9, True, 'Mrs_Nicholas_(Adele_Achem)_Nasser', True, 14),\n",
       " (10, True, 'Miss_Marguerite_Rut_Sandstrom', True, 4),\n",
       " (11, True, 'Miss_Elizabeth_Bonnell', True, 58),\n",
       " (12, False, 'Mr_William_Henry_Saundercock', False, 20),\n",
       " (13, False, 'Mr_Anders_Johan_Andersson', False, 39),\n",
       " (14, False, 'Miss_Hulda_Amanda_Adolfina_Vestrom', True, 14),\n",
       " (15, True, 'Mrs_(Mary_D_Kingcome)_Hewlett', True, 55),\n",
       " (16, False, 'Master_Eugene_Rice', False, 2),\n",
       " (17, True, 'Mr_Charles_Eugene_Williams', False, 23),\n",
       " (18,\n",
       "  False,\n",
       "  'Mrs_Julius_(Emelia_Maria_Vandemoortele)_Vander_Planke',\n",
       "  True,\n",
       "  31),\n",
       " (19, True, 'Mrs_Fatima_Masselmani', True, 22),\n",
       " (20, False, 'Mr_Joseph_J_Fynney', False, 35),\n",
       " (21, True, 'Mr_Lawrence_Beesley', False, 34),\n",
       " (22, True, 'Miss_Anna_McGowan', True, 15),\n",
       " (23, True, 'Mr_William_Thompson_Sloper', False, 28),\n",
       " (24, False, 'Miss_Torborg_Danira_Palsson', True, 8),\n",
       " (25,\n",
       "  True,\n",
       "  'Mrs_Carl_Oscar_(Selma_Augusta_Emilia_Johansson)_Asplund',\n",
       "  True,\n",
       "  38),\n",
       " (26, False, 'Mr_Farred_Chehab_Emir', False, 26),\n",
       " (27, False, 'Mr_Charles_Alexander_Fortune', False, 19),\n",
       " (28, True, 'Miss_Ellen_ODwyer', True, 24),\n",
       " (29, False, 'Mr_Lalio_Todoroff', False, 23),\n",
       " (30, False, 'Don_Manuel_E_Uruchurtu', False, 40),\n",
       " (31, True, 'Mrs_William_Augustus_(Marie_Eugenie)_Spencer', True, 48),\n",
       " (32, True, 'Miss_Mary_Agatha_Glynn', True, 18),\n",
       " (33, False, 'Mr_Edward_H_Wheadon', False, 66),\n",
       " (34, False, 'Mr_Edgar_Joseph_Meyer', False, 28),\n",
       " (35, False, 'Mr_Alexander_Oskar_Holverson', False, 42),\n",
       " (36, True, 'Mr_Hanna_Mamee', False, 18),\n",
       " (37, False, 'Mr_Ernest_Charles_Cann', False, 21),\n",
       " (38, False, 'Miss_Augusta_Maria_Vander_Planke', True, 18),\n",
       " (39, True, 'Miss_Jamila_Nicola-Yarred', True, 14),\n",
       " (40, False, 'Mrs_Johan_(Johanna_Persdotter_Larsson)_Ahlin', True, 40),\n",
       " (41,\n",
       "  False,\n",
       "  'Mrs_William_John_Robert_(Dorothy_Ann_Wonnacott)_Turpin',\n",
       "  True,\n",
       "  27),\n",
       " (42, True, 'Miss_Simonne_Marie_Anne_Andree_Laroche', True, 3),\n",
       " (43, True, 'Miss_Margaret_Delia_Devaney', True, 19),\n",
       " (44, False, 'Mr_William_John_Rogers', False, 30),\n",
       " (45, False, 'Mr_Denis_Lennon', False, 20),\n",
       " (46, True, 'Miss_Bridget_ODriscoll', True, 27),\n",
       " (47, False, 'Mr_Youssef_Samaan', False, 16),\n",
       " (48, False, 'Mrs_Josef_(Josefine_Franchi)_Arnold-Franchi', True, 18),\n",
       " (49, False, 'Master_Juha_Niilo_Panula', False, 7),\n",
       " (50, False, 'Mr_Richard_Cater_Nosworthy', False, 21),\n",
       " (51, True, 'Mrs_Henry_Sleeper_(Myna_Haxtun)_Harper', True, 49),\n",
       " (176, False, 'Miss_Ann_Elizabeth_Isham', True, 50),\n",
       " (52, True, 'Mrs_Lizzie_(Elizabeth_Anne_Wilkinson)_Faunthorpe', True, 29),\n",
       " (53, False, 'Mr_Engelhart_Cornelius_Ostby', False, 65),\n",
       " (54, True, 'Mr_Hugh_Woolner', False, 46),\n",
       " (55, True, 'Miss_Emily_Rugg', True, 21),\n",
       " (56, False, 'Mr_Mansouer_Novel', False, 29),\n",
       " (57, True, 'Miss_Constance_Mirium_West', True, 5),\n",
       " (58, False, 'Master_William_Frederick_Goodwin', False, 11),\n",
       " (59, False, 'Mr_Orsen_Sirayanian', False, 22),\n",
       " (60, True, 'Miss_Amelie_Icard', True, 38),\n",
       " (61, False, 'Mr_Henry_Birkhardt_Harris', False, 45),\n",
       " (62, False, 'Master_Harald_Skoog', False, 4),\n",
       " (63, False, 'Mr_Albert_A_Stewart', False, 64),\n",
       " (64, True, 'Master_Gerios_Moubarek', False, 7),\n",
       " (65, True, 'Mrs_(Elizabeth_Ramell)_Nye', True, 29),\n",
       " (66, False, 'Mr_Ernest_James_Crease', False, 19),\n",
       " (67, True, 'Miss_Erna_Alexandra_Andersson', True, 17),\n",
       " (68, False, 'Mr_Vincenz_Kink', False, 26),\n",
       " (69, False, 'Mr_Stephen_Curnow_Jenkin', False, 32),\n",
       " (70, False, 'Miss_Lillian_Amy_Goodwin', True, 16),\n",
       " (71, False, 'Mr_Ambrose_Jr_Hood', False, 21),\n",
       " (72, False, 'Mr_Apostolos_Chronopoulos', False, 26),\n",
       " (73, True, 'Mr_Lee_Bing', False, 32),\n",
       " (74, False, 'Mr_Sigurd_Hansen_Moen', False, 25),\n",
       " (75, False, 'Mr_Ivan_Staneff', False, 23),\n",
       " (76, False, 'Mr_Rahamin_Haim_Moutal', False, 28),\n",
       " (77, True, 'Master_Alden_Gates_Caldwell', False, 1),\n",
       " (78, True, 'Miss_Elizabeth_Dowdell', True, 30),\n",
       " (79, False, 'Mr_Achille_Waelens', False, 22),\n",
       " (80, True, 'Mr_Jan_Baptist_Sheerlinck', False, 29),\n",
       " (81, True, 'Miss_Brigdet_Delia_McDermott', True, 31),\n",
       " (82, False, 'Mr_Francisco_M_Carrau', False, 28),\n",
       " (83, True, 'Miss_Bertha_Ilett', True, 17),\n",
       " (84, True, 'Mrs_Karl_Alfred_(Maria_Mathilda_Gustafsson)_Backstrom', True, 33),\n",
       " (85, False, 'Mr_William_Neal_Ford', False, 16),\n",
       " (86, False, 'Mr_Selman_Francis_Slocovski', False, 20),\n",
       " (87, True, 'Miss_Mabel_Helen_Fortune', True, 23),\n",
       " (88, False, 'Mr_Francesco_Celotti', False, 24),\n",
       " (89, False, 'Mr_Emil_Christmann', False, 29),\n",
       " (90, False, 'Mr_Paul_Edvin_Andreasson', False, 20),\n",
       " (91, False, 'Mr_Herbert_Fuller_Chaffee', False, 46),\n",
       " (92, False, 'Mr_Bertram_Frank_Dean', False, 26),\n",
       " (93, False, 'Mr_Daniel_Coxon', False, 59),\n",
       " (94, False, 'Mr_Charles_Joseph_Shorney', False, 22),\n",
       " (95, False, 'Mr_George_B_Goldschmidt', False, 71),\n",
       " (96, True, 'Mr_William_Bertram_Greenfield', False, 23),\n",
       " (97, True, 'Mrs_John_T_(Ada_Julia_Bone)_Doling', True, 34),\n",
       " (98, False, 'Mr_Sinai_Kantor', False, 34),\n",
       " (99, False, 'Miss_Matilda_Petranec', True, 28),\n",
       " (100, False, 'Mr_Pastcho_Petroff', False, 29),\n",
       " (101, False, 'Mr_Richard_Frasar_White', False, 21),\n",
       " (102, False, 'Mr_Gustaf_Joel_Johansson', False, 33),\n",
       " (103, False, 'Mr_Anders_Vilhelm_Gustafsson', False, 37),\n",
       " (104, False, 'Mr_Stoytcho_Mionoff', False, 28),\n",
       " (105, True, 'Miss_Anna_Kristine_Salkjelsvik', True, 21),\n",
       " (106, True, 'Mr_Albert_Johan_Moss', False, 29),\n",
       " (107, False, 'Mr_Tido_Rekic', False, 38),\n",
       " (108, True, 'Miss_Bertha_Moran', True, 28),\n",
       " (109, False, 'Mr_Walter_Chamberlain_Porter', False, 47),\n",
       " (110, False, 'Miss_Hileni_Zabour', True, 15),\n",
       " (111, False, 'Mr_David_John_Barton', False, 22),\n",
       " (112, False, 'Miss_Katriina_Jussila', True, 20),\n",
       " (113, False, 'Miss_Malake_Attalah', True, 17),\n",
       " (114, False, 'Mr_Edvard_Pekoniemi', False, 21),\n",
       " (115, False, 'Mr_Patrick_Connors', False, 71),\n",
       " (116, False, 'Mr_William_John_Robert_Turpin', False, 29),\n",
       " (117, False, 'Mr_Quigg_Edmond_Baxter', False, 24),\n",
       " (118, False, 'Miss_Ellis_Anna_Maria_Andersson', True, 2),\n",
       " (119, False, 'Mr_Stanley_George_Hickman', False, 21),\n",
       " (120, False, 'Mr_Leonard_Charles_Moore', False, 19),\n",
       " (121, False, 'Mr_Nicholas_Nasser', False, 33),\n",
       " (122, True, 'Miss_Susan_Webber', True, 33),\n",
       " (123, False, 'Mr_Percival_Wayland_White', False, 54),\n",
       " (124, True, 'Master_Elias_Nicola-Yarred', False, 12),\n",
       " (125, False, 'Mr_Martin_McMahon', False, 19),\n",
       " (126, True, 'Mr_Fridtjof_Arne_Madsen', False, 24),\n",
       " (127, True, 'Miss_Anna_Peter', True, 2),\n",
       " (128, False, 'Mr_Johan_Ekstrom', False, 45),\n",
       " (129, False, 'Mr_Jozef_Drazenoic', False, 33),\n",
       " (130, False, 'Mr_Domingos_Fernandeo_Coelho', False, 20),\n",
       " (131, False, 'Mrs_Alexander_A_(Grace_Charity_Laury)_Robins', True, 47),\n",
       " (132, True, 'Mrs_Leopold_(Mathilde_Francoise_Pede)_Weisz', True, 29),\n",
       " (133, False, 'Mr_Samuel_James_Hayden_Sobey', False, 25),\n",
       " (134, False, 'Mr_Emile_Richard', False, 23),\n",
       " (135, True, 'Miss_Helen_Monypeny_Newsom', True, 19),\n",
       " (136, False, 'Mr_Jacques_Heath_Futrelle', False, 37),\n",
       " (137, False, 'Mr_Olaf_Elon_Osen', False, 16),\n",
       " (138, False, 'Mr_Victor_Giglio', False, 24),\n",
       " (139, False, 'Mrs_Joseph_(Sultana)_Boulos', True, 40),\n",
       " (140, True, 'Miss_Anna_Sofia_Nysten', True, 22),\n",
       " (141, True, 'Mrs_Pekka_Pietari_(Elin_Matilda_Dolck)_Hakkarainen', True, 24),\n",
       " (142, False, 'Mr_Jeremiah_Burke', False, 19),\n",
       " (143, False, 'Mr_Edgardo_Samuel_Andrew', False, 18),\n",
       " (144, False, 'Mr_Joseph_Charles_Nicholls', False, 19),\n",
       " (145, True, 'Mr_August_Edvard_Andersson', False, 27),\n",
       " (146, False, 'Miss_Robina_Maggie_Ford', True, 9),\n",
       " (147, False, 'Mr_Michel_Navratil', False, 37),\n",
       " (148, False, 'Rev_Thomas_Roussel_Davids_Byles', False, 42),\n",
       " (149, False, 'Rev_Robert_James_Bateman', False, 51),\n",
       " (150, True, 'Mrs_Thomas_(Edith_Wearne)_Pears', True, 22),\n",
       " (151, False, 'Mr_Alfonzo_Meo', False, 56),\n",
       " (152, False, 'Mr_Austin_Blyler_van_Billiard', False, 41),\n",
       " (153, False, 'Mr_Ole_Martin_Olsen', False, 27),\n",
       " (154, False, 'Mr_Charles_Duane_Williams', False, 51),\n",
       " (155, True, 'Miss_Katherine_Gilnagh', True, 16),\n",
       " (156, False, 'Mr_Harry_Corn', False, 30),\n",
       " (157, False, 'Mr_Mile_Smiljanic', False, 37),\n",
       " (158, False, 'Master_Thomas_Henry_Sage', False, 5),\n",
       " (159, False, 'Mr_John_Hatfield_Cribb', False, 44),\n",
       " (160, True, 'Mrs_James_(Elizabeth_Inglis_Milne)_Watt', True, 40),\n",
       " (161, False, 'Mr_John_Viktor_Bengtsson', False, 26),\n",
       " (162, False, 'Mr_Jovo_Calic', False, 17),\n",
       " (163, False, 'Master_Eino_Viljami_Panula', False, 1),\n",
       " (164, True, 'Master_Frank_John_William_Goldsmith', False, 9),\n",
       " (165, True, 'Mrs_(Edith_Martha_Bowerman)_Chibnall', True, 48),\n",
       " (166, False, 'Mrs_William_(Anna_Bernhardina_Karlsson)_Skoog', True, 45),\n",
       " (167, False, 'Mr_John_D_Baumann', False, 60),\n",
       " (168, False, 'Mr_Lee_Ling', False, 28),\n",
       " (169, False, 'Mr_Wyckoff_Van_der_hoef', False, 61),\n",
       " (170, False, 'Master_Arthur_Rice', False, 4),\n",
       " (171, True, 'Miss_Eleanor_Ileen_Johnson', True, 1),\n",
       " (172, False, 'Mr_Antti_Wilhelm_Sivola', False, 21),\n",
       " (173, False, 'Mr_James_Clinch_Smith', False, 56),\n",
       " (174, False, 'Mr_Klas_Albin_Klasen', False, 18),\n",
       " (175, False, 'Master_Henry_Forbes_Lefebre', False, 5),\n",
       " (177, False, 'Mr_Reginald_Hale', False, 30),\n",
       " (178, False, 'Mr_Lionel_Leonard', False, 36),\n",
       " (179, False, 'Miss_Constance_Gladys_Sage', True, 8),\n",
       " (180, False, 'Mr_Rene_Pernot', False, 39),\n",
       " (181, False, 'Master_Clarence_Gustaf_Hugo_Asplund', False, 9),\n",
       " (182, True, 'Master_Richard_F_Becker', False, 1),\n",
       " (183, True, 'Miss_Luise_Gretchen_Kink-Heilmann', True, 4),\n",
       " (184, False, 'Mr_Hugh_Roscoe_Rood', False, 39),\n",
       " (185, True, 'Mrs_Thomas_(Johanna_Godfrey)_OBrien', True, 26),\n",
       " (186, True, 'Mr_Charles_Hallace_Romaine', False, 45),\n",
       " (187, False, 'Mr_John_Bourke', False, 40),\n",
       " (188, False, 'Mr_Stjepan_Turcin', False, 36),\n",
       " (189, True, 'Mrs_(Rosa)_Pinsky', True, 32),\n",
       " (190, False, 'Mr_William_Carbines', False, 19),\n",
       " (191, True, 'Miss_Carla_Christine_Nielsine_Andersen-Jensen', True, 19),\n",
       " (192, True, 'Master_Michel_M_Navratil', False, 3),\n",
       " (193, True, 'Mrs_James_Joseph_(Margaret_Tobin)_Brown', True, 44),\n",
       " (194, True, 'Miss_Elise_Lurette', True, 58),\n",
       " (195, False, 'Mr_Robert_Mernagh', False, 28),\n",
       " (196, False, 'Mr_Karl_Siegwart_Andreas_Olsen', False, 42),\n",
       " (197, True, 'Miss_Margaret_Madigan', True, 21),\n",
       " (198, False, 'Miss_Henriette_Yrois', True, 24),\n",
       " (199, False, 'Mr_Nestor_Cyriel_Vande_Walle', False, 28),\n",
       " (200, False, 'Mr_Frederick_Sage', False, 17),\n",
       " (201, False, 'Mr_Jakob_Alfred_Johanson', False, 34),\n",
       " (202, False, 'Mr_Gerious_Youseff', False, 46),\n",
       " (203, True, 'Mr_Gurshon_Cohen', False, 18),\n",
       " (204, False, 'Miss_Telma_Matilda_Strom', True, 2),\n",
       " (205, False, 'Mr_Karl_Alfred_Backstrom', False, 32),\n",
       " (206, True, 'Mr_Nassef_Cassem_Albimona', False, 26),\n",
       " (207, True, 'Miss_Helen_Carr', True, 16),\n",
       " (208, True, 'Mr_Henry_Blank', False, 40),\n",
       " (209, False, 'Mr_Ahmed_Ali', False, 24),\n",
       " (210, True, 'Miss_Clear_Annie_Cameron', True, 35),\n",
       " (211, False, 'Mr_John_Henry_Perkin', False, 22),\n",
       " (212, False, 'Mr_Hans_Kristensen_Givard', False, 30),\n",
       " (213, False, 'Mr_Philip_Kiernan', False, 22),\n",
       " (214, True, 'Miss_Madeleine_Newell', True, 31),\n",
       " (215, True, 'Miss_Eliina_Honkanen', True, 27),\n",
       " (216, False, 'Mr_Sidney_Samuel_Jacobsohn', False, 42),\n",
       " (217, True, 'Miss_Albina_Bazzani', True, 32),\n",
       " (218, False, 'Mr_Walter_Harris', False, 30),\n",
       " (219, True, 'Mr_Victor_Francis_Sunderland', False, 16),\n",
       " (220, False, 'Mr_James_H_Bracken', False, 27),\n",
       " (221, False, 'Mr_George_Henry_Green', False, 51),\n",
       " (222, False, 'Mr_Christo_Nenkoff', False, 22),\n",
       " (223, True, 'Mr_Frederick_Maxfield_Hoyt', False, 38),\n",
       " (224, False, 'Mr_Karl_Ivar_Sven_Berglund', False, 22),\n",
       " (225, True, 'Mr_William_John_Mellors', False, 19),\n",
       " (226, False, 'Mr_John_Hall_Lovell', False, 21),\n",
       " (227, False, 'Mr_Arne_Jonas_Fahlstrom', False, 18),\n",
       " (228, False, 'Miss_Mathilde_Lefebre', True, 12),\n",
       " (229, True, 'Mrs_Henry_Birkhardt_(Irene_Wallach)_Harris', True, 35),\n",
       " (230, False, 'Mr_Bengt_Edvin_Larsson', False, 29),\n",
       " (231, False, 'Mr_Ernst_Adolf_Sjostedt', False, 59),\n",
       " (232, True, 'Miss_Lillian_Gertrud_Asplund', True, 5),\n",
       " (233, False, 'Mr_Robert_William_Norman_Leyson', False, 24),\n",
       " (234, False, 'Miss_Alice_Phoebe_Harknett', True, 21),\n",
       " (235, False, 'Mr_Stephen_Hold', False, 44),\n",
       " (236, True, 'Miss_Marjorie_Collyer', True, 8),\n",
       " (237, False, 'Mr_Frederick_William_Pengelly', False, 19),\n",
       " (238, False, 'Mr_George_Henry_Hunt', False, 33),\n",
       " (239, False, 'Miss_Thamine_Zabour', True, 19),\n",
       " (240, True, 'Miss_Katherine_Murphy', True, 18),\n",
       " (241, False, 'Mr_Reginald_Charles_Coleridge', False, 29),\n",
       " (242, False, 'Mr_Matti_Alexanteri_Maenpaa', False, 22),\n",
       " (243, False, 'Mr_Sleiman_Attalah', False, 30),\n",
       " (244, False, 'Dr_William_Edward_Minahan', False, 44),\n",
       " (245, False, 'Miss_Agda_Thorilda_Viktoria_Lindahl', True, 25),\n",
       " (246, True, 'Mrs_William_(Anna)_Hamalainen', True, 24),\n",
       " (247, True, 'Mr_Richard_Leonard_Beckwith', False, 37),\n",
       " (248, False, 'Rev_Ernest_Courtenay_Carter', False, 54),\n",
       " (249, False, 'Mr_James_George_Reed', False, 18),\n",
       " (250, False, 'Mrs_Wilhelm_(Elna_Matilda_Persson)_Strom', True, 29),\n",
       " (251, False, 'Mr_William_Thomas_Stead', False, 62),\n",
       " (252, False, 'Mr_William_Arthur_Lobb', False, 30),\n",
       " (253, False, 'Mrs_Viktor_(Helena_Wilhelmina)_Rosblom', True, 41),\n",
       " (254, True, 'Mrs_Darwis_(Hanne_Youssef_Razi)_Touma', True, 29),\n",
       " (255, True, 'Mrs_Gertrude_Maybelle_Thorne', True, 38),\n",
       " (256, True, 'Miss_Gladys_Cherry', True, 30),\n",
       " (257, True, 'Miss_Anna_Ward', True, 35),\n",
       " (258, True, 'Mrs_(Lutie_Davis)_Parrish', True, 50),\n",
       " (259, True, 'Master_Edvin_Rojj_Felix_Asplund', False, 3),\n",
       " (260, False, 'Mr_Emil_Taussig', False, 52),\n",
       " (261, False, 'Mr_William_Harrison', False, 40),\n",
       " (262, False, 'Miss_Delia_Henry', True, 21),\n",
       " (263, False, 'Mr_David_Reeves', False, 36),\n",
       " (264, False, 'Mr_Ernesti_Arvid_Panula', False, 16),\n",
       " (265, True, 'Mr_Ernst_Ulrik_Persson', False, 25),\n",
       " (266, True, 'Mrs_William_Thompson_(Edith_Junkins)_Graham', True, 58),\n",
       " (267, True, 'Miss_Amelia_Bissette', True, 35),\n",
       " (268, False, 'Mr_Alexander_Cairns', False, 28),\n",
       " (269, True, 'Mr_William_Henry_Tornquist', False, 25),\n",
       " (270, True, 'Mrs_(Elizabeth_Anne_Maidment)_Mellinger', True, 41),\n",
       " (271, False, 'Mr_Charles_H_Natsch', False, 37),\n",
       " (272, True, 'Miss_Hanora_Healy', True, 33),\n",
       " (273, True, 'Miss_Kornelia_Theodosia_Andrews', True, 63),\n",
       " (274, False, 'Miss_Augusta_Charlotta_Lindblom', True, 45),\n",
       " (275, False, 'Mr_Francis_Parkes', False, 21),\n",
       " (276, False, 'Master_Eric_Rice', False, 7),\n",
       " (277, True, 'Mrs_Stanton_(Rosa_Hunt)_Abbott', True, 35),\n",
       " (278, False, 'Mr_Frank_Duane', False, 65),\n",
       " (279, False, 'Mr_Nils_Johan_Goransson_Olsson', False, 28),\n",
       " (280, False, 'Mr_Alfons_de_Pelsmaeker', False, 16),\n",
       " (281, True, 'Mr_Edward_Arthur_Dorking', False, 19),\n",
       " (282, False, 'Mr_Richard_William_Smith', False, 57),\n",
       " (283, False, 'Mr_Ivan_Stankovic', False, 33),\n",
       " (284, True, 'Mr_Theodore_de_Mulder', False, 30),\n",
       " (285, False, 'Mr_Penko_Naidenoff', False, 22),\n",
       " (286, True, 'Mr_Masabumi_Hosono', False, 42),\n",
       " (287, True, 'Miss_Kate_Connolly', True, 22),\n",
       " (288, True, 'Miss_Ellen_Barber', True, 26),\n",
       " (289, True, 'Mrs_Dickinson_H_(Helen_Walton)_Bishop', True, 19),\n",
       " (290, False, 'Mr_Rene_Jacques_Levy', False, 36),\n",
       " (291, False, 'Miss_Aloisia_Haas', True, 24),\n",
       " (292, False, 'Mr_Ivan_Mineff', False, 24),\n",
       " (293, False, 'Mr_Ervin_G_Lewy', False, 30),\n",
       " (294, False, 'Mr_Mansour_Hanna', False, 24),\n",
       " (295, False, 'Miss_Helen_Loraine_Allison', True, 2),\n",
       " (296, True, 'Mr_Adolphe_Saalfeld', False, 47),\n",
       " (297, True, 'Mrs_James_(Helene_DeLaudeniere_Chaput)_Baxter', True, 50),\n",
       " (298, True, 'Miss_Anna_Katherine_Kelly', True, 20),\n",
       " (299, True, 'Mr_Bernard_McCoy', False, 24),\n",
       " (300, False, 'Mr_William_Cahoone_Jr_Johnson', False, 19),\n",
       " (301, True, 'Miss_Nora_A_Keane', True, 46),\n",
       " (302, False, 'Mr_Howard_Hugh_Williams', False, 28),\n",
       " (303, True, 'Master_Hudson_Trevor_Allison', False, 1),\n",
       " (304, True, 'Miss_Margaret_Fleming', True, 42),\n",
       " (305,\n",
       "  True,\n",
       "  'Mrs_Victor_de_Satode_(Maria_Josefa_Perez_de_Soto_y_Vallejo)_Penasco_y_Castellana',\n",
       "  True,\n",
       "  17),\n",
       " (306, False, 'Mr_Samuel_Abelson', False, 30),\n",
       " (307, True, 'Miss_Laura_Mabel_Francatelli', True, 30),\n",
       " (308, True, 'Miss_Margaret_Bechstein_Hays', True, 24),\n",
       " (309, True, 'Miss_Emily_Borie_Ryerson', True, 18),\n",
       " (310, False, 'Mrs_William_(Anna_Sylfven)_Lahtinen', True, 26),\n",
       " (311, False, 'Mr_Ignjac_Hendekovic', False, 28),\n",
       " (312, False, 'Mr_Benjamin_Hart', False, 43),\n",
       " (313, True, 'Miss_Helmina_Josefina_Nilsson', True, 26),\n",
       " (314, True, 'Mrs_Sinai_(Miriam_Sternin)_Kantor', True, 24),\n",
       " (315, False, 'Dr_Ernest_Moraweck', False, 54),\n",
       " (316, True, 'Miss_Mary_Natalie_Wick', True, 31),\n",
       " (317,\n",
       "  True,\n",
       "  'Mrs_Frederic_Oakley_(Margaretta_Corning_Stone)_Spedden',\n",
       "  True,\n",
       "  40),\n",
       " (318, False, 'Mr_Samuel_Dennis', False, 22),\n",
       " (319, False, 'Mr_Yoto_Danoff', False, 27),\n",
       " (320, True, 'Miss_Hilda_Mary_Slayter', True, 30),\n",
       " (321, True, 'Mrs_Albert_Francis_(Sylvia_Mae_Harbaugh)_Caldwell', True, 22),\n",
       " (322, False, 'Mr_George_John_Jr_Sage', False, 20),\n",
       " (323, True, 'Miss_Marie_Grice_Young', True, 36),\n",
       " (324, False, 'Mr_Johan_Hansen_Nysveen', False, 61),\n",
       " (325, True, 'Mrs_(Ada_E_Hall)_Ball', True, 36),\n",
       " (326, True, 'Mrs_Frank_John_(Emily_Alice_Brown)_Goldsmith', True, 31),\n",
       " (327, True, 'Miss_Jean_Gertrude_Hippach', True, 16),\n",
       " (328, True, 'Miss_Agnes_McCoy', True, 28),\n",
       " (329, False, 'Mr_Austen_Partner', False, 46),\n",
       " (330, False, 'Mr_George_Edward_Graham', False, 38),\n",
       " (331, False, 'Mr_Leo_Edmondus_Vander_Planke', False, 16),\n",
       " (332, True, 'Mrs_Henry_William_(Clara_Heinsheimer)_Frauenthal', True, 42),\n",
       " (333, False, 'Mr_Mitto_Denkoff', False, 30),\n",
       " (334, False, 'Mr_Thomas_Clinton_Pears', False, 29),\n",
       " (335, True, 'Miss_Elizabeth_Margaret_Burns', True, 41),\n",
       " (336, True, 'Mr_Karl_Edwart_Dahl', False, 45),\n",
       " (337, False, 'Mr_Stephen_Weart_Blackwell', False, 45),\n",
       " (338, True, 'Master_Edmond_Roger_Navratil', False, 2),\n",
       " (339, True, 'Miss_Alice_Elizabeth_Fortune', True, 24),\n",
       " (340, False, 'Mr_Erik_Gustaf_Collander', False, 28),\n",
       " (341, False, 'Mr_Charles_Frederick_Waddington_Sedgwick', False, 25),\n",
       " (342, False, 'Mr_Stanley_Hubert_Fox', False, 36),\n",
       " (343, True, 'Miss_Amelia_Brown', True, 24),\n",
       " (344, True, 'Miss_Marion_Elsie_Smith', True, 40),\n",
       " (345, True, 'Mrs_Thomas_Henry_(Mary_E_Finck)_Davison', True, 34),\n",
       " (346, True, 'Master_William_Loch_Coutts', False, 3),\n",
       " (347, False, 'Mr_Jovan_Dimic', False, 42),\n",
       " (348, False, 'Mr_Nils_Martin_Odahl', False, 23),\n",
       " (349, False, 'Mr_Fletcher_Fellows_Williams-Lambert', False, 43),\n",
       " (350, False, 'Mr_Tannous_Elias', False, 15),\n",
       " (351, False, 'Mr_Josef_Arnold-Franchi', False, 25),\n",
       " (352, False, 'Mr_Wazli_Yousif', False, 23),\n",
       " (353, False, 'Mr_Leo_Peter_Vanden_Steen', False, 28),\n",
       " (354, True, 'Miss_Elsie_Edith_Bowerman', True, 22),\n",
       " (355, False, 'Miss_Annie_Clemmer_Funk', True, 38),\n",
       " (356, True, 'Miss_Mary_McGovern', True, 22),\n",
       " (357, True, 'Miss_Helen_Mary_Mockler', True, 23),\n",
       " (358, False, 'Mr_Wilhelm_Skoog', False, 40),\n",
       " (359, False, 'Mr_Sebastiano_del_Carlo', False, 29),\n",
       " (360, False, 'Mrs_(Catherine_David)_Barbara', True, 45),\n",
       " (361, False, 'Mr_Adola_Asim', False, 35),\n",
       " (362, False, 'Mr_Thomas_OBrien', False, 27),\n",
       " (363, False, 'Mr_Mauritz_Nils_Martin_Adahl', False, 30),\n",
       " (364, True, 'Mrs_Frank_Manley_(Anna_Sophia_Atkinson)_Warren', True, 60),\n",
       " (365, True, 'Mrs_(Mantoura_Boulos)_Moussa', True, 35),\n",
       " (366, True, 'Miss_Annie_Jermyn', True, 22),\n",
       " (367, True, 'Mme_Leontine_Pauline_Aubart', True, 24),\n",
       " (368, True, 'Mr_George_Achilles_Harder', False, 25),\n",
       " (369, False, 'Mr_Jakob_Alfred_Wiklund', False, 18),\n",
       " (370, False, 'Mr_William_Thomas_Beavan', False, 19),\n",
       " (371, False, 'Mr_Sante_Ringhini', False, 22),\n",
       " (372, False, 'Miss_Stina_Viola_Palsson', True, 3),\n",
       " (373, True, 'Mrs_Edgar_Joseph_(Leila_Saks)_Meyer', True, 25),\n",
       " (374, True, 'Miss_Aurora_Adelia_Landergren', True, 22),\n",
       " (375, False, 'Mr_Harry_Elkins_Widener', False, 27),\n",
       " (376, False, 'Mr_Tannous_Betros', False, 20),\n",
       " (377, False, 'Mr_Karl_Gideon_Gustafsson', False, 19),\n",
       " (378, True, 'Miss_Rosalie_Bidois', True, 42),\n",
       " (379, True, 'Miss_Maria_Nakid', True, 1),\n",
       " (380, False, 'Mr_Juho_Tikkanen', False, 32),\n",
       " (381, True, 'Mrs_Alexander_Oskar_(Mary_Aline_Towner)_Holverson', True, 35),\n",
       " (382, False, 'Mr_Vasil_Plotcharsky', False, 27),\n",
       " (383, False, 'Mr_Charles_Henry_Davies', False, 18),\n",
       " (384, False, 'Master_Sidney_Leonard_Goodwin', False, 1),\n",
       " (385, True, 'Miss_Kate_Buss', True, 36),\n",
       " (386, False, 'Mr_Matthew_Sadlier', False, 19),\n",
       " (387, True, 'Miss_Bertha_Lehmann', True, 17),\n",
       " (388, True, 'Mr_William_Ernest_Carter', False, 36),\n",
       " (389, True, 'Mr_Carl_Olof_Jansson', False, 21),\n",
       " (390, False, 'Mr_Johan_Birger_Gustafsson', False, 28),\n",
       " (391, True, 'Miss_Marjorie_Newell', True, 23),\n",
       " (392, True, 'Mrs_Hjalmar_(Agnes_Charlotta_Bengtsson)_Sandstrom', True, 24),\n",
       " (393, False, 'Mr_Erik_Johansson', False, 22),\n",
       " (394, False, 'Miss_Elina_Olsson', True, 31),\n",
       " (395, False, 'Mr_Peter_David_McKane', False, 46),\n",
       " (396, False, 'Dr_Alfred_Pain', False, 23),\n",
       " (397, True, 'Mrs_William_H_(Jessie_L)_Trout', True, 28),\n",
       " (398, True, 'Mr_Juha_Niskanen', False, 39),\n",
       " (399, False, 'Mr_John_Adams', False, 26),\n",
       " (400, False, 'Miss_Mari_Aina_Jussila', True, 21),\n",
       " (401, False, 'Mr_Pekka_Pietari_Hakkarainen', False, 28),\n",
       " (402, False, 'Miss_Marija_Oreskovic', True, 20),\n",
       " (403, False, 'Mr_Shadrach_Gale', False, 34),\n",
       " (404, False, 'Mr_Carl/Charles_Peter_Widegren', False, 51),\n",
       " (405, True, 'Master_William_Rowe_Richards', False, 3),\n",
       " (406, False, 'Mr_Hans_Martin_Monsen_Birkeland', False, 21),\n",
       " (407, False, 'Miss_Ida_Lefebre', True, 3),\n",
       " (408, False, 'Mr_Todor_Sdycoff', False, 42),\n",
       " (409, False, 'Mr_Henry_Hart', False, 27),\n",
       " (410, True, 'Miss_Daisy_E_Minahan', True, 33),\n",
       " (411, False, 'Mr_Alfred_Fleming_Cunningham', False, 22),\n",
       " (412, True, 'Mr_Johan_Julian_Sundman', False, 44),\n",
       " (413, False, 'Mrs_Thomas_(Annie_Louise_Rowley)_Meek', True, 32),\n",
       " (414, True, 'Mrs_James_Vivian_(Lulu_Thorne_Christian)_Drew', True, 34),\n",
       " (415, True, 'Miss_Lyyli_Karoliina_Silven', True, 18),\n",
       " (416, False, 'Mr_William_John_Matthews', False, 30),\n",
       " (417, False, 'Miss_Catharina_Van_Impe', True, 10),\n",
       " (418, False, 'Mr_David_Charters', False, 21),\n",
       " (419, False, 'Mr_Leo_Zimmerman', False, 29),\n",
       " (420,\n",
       "  False,\n",
       "  'Mrs_Ernst_Gilbert_(Anna_Sigrid_Maria_Brogren)_Danbom',\n",
       "  True,\n",
       "  28),\n",
       " (421, False, 'Mr_Viktor_Richard_Rosblom', False, 18),\n",
       " (422, False, 'Mr_Phillippe_Wiseman', False, 54),\n",
       " (423, True, 'Mrs_Charles_V_(Ada_Maria_Winfield)_Clarke', True, 28),\n",
       " (424, True, 'Miss_Kate_Florence_Phillips', True, 19),\n",
       " (425, False, 'Mr_James_Flynn', False, 28),\n",
       " (426, True, 'Mr_Berk_(Berk_Trembisky)_Pickard', False, 32),\n",
       " (427, True, 'Mr_Mauritz_Hakan_Bjornstrom-Steffansson', False, 28),\n",
       " (428, True, 'Mrs_Percival_(Florence_Kate_White)_Thorneycroft', True, 33),\n",
       " (429, True, 'Mrs_Charles_Alexander_(Alice_Adelaide_Slow)_Louch', True, 42),\n",
       " (430, False, 'Mr_Nikolai_Erland_Kallio', False, 17),\n",
       " (431, False, 'Mr_William_Baird_Silvey', False, 50),\n",
       " (432, True, 'Miss_Lucile_Polk_Carter', True, 14),\n",
       " (433, False, 'Miss_Doolina_Margaret_Ford', True, 21),\n",
       " (434, True, 'Mrs_Sidney_(Emily_Hocking)_Richards', True, 24),\n",
       " (435, False, 'Mr_Mark_Fortune', False, 64),\n",
       " (436, False, 'Mr_Johan_Henrik_Johannesson_Kvillner', False, 31),\n",
       " (437, True, 'Mrs_Benjamin_(Esther_Ada_Bloomfield)_Hart', True, 45),\n",
       " (438, False, 'Mr_Leon_Hampe', False, 20),\n",
       " (439, False, 'Mr_Johan_Emil_Petterson', False, 25),\n",
       " (440, True, 'Ms_Encarnacion_Reynaldo', True, 28),\n",
       " (441, True, 'Mr_Bernt_Johannesen-Bratthammer', False, 29),\n",
       " (442, True, 'Master_Washington_Dodge', False, 4),\n",
       " (443, True, 'Miss_Madeleine_Violet_Mellinger', True, 13),\n",
       " (444, True, 'Mr_Frederic_Kimber_Seward', False, 34),\n",
       " (445, True, 'Miss_Marie_Catherine_Baclini', True, 5),\n",
       " (446, True, 'Major_Arthur_Godfrey_Peuchen', False, 52),\n",
       " (447, False, 'Mr_Edwy_Arthur_West', False, 36),\n",
       " (448, False, 'Mr_Ingvald_Olai_Olsen_Hagland', False, 28),\n",
       " (449, False, 'Mr_Benjamin_Laventall_Foreman', False, 30),\n",
       " (450, True, 'Mr_Samuel_L_Goldenberg', False, 49),\n",
       " (451, False, 'Mr_Joseph_Peduzzi', False, 24),\n",
       " (452, True, 'Mr_Ivan_Jalsevac', False, 29),\n",
       " (453, False, 'Mr_Francis_Davis_Millet', False, 65),\n",
       " (454, True, 'Mrs_Frederick_R_(Marion)_Kenyon', True, 41),\n",
       " (455, True, 'Miss_Ellen_Toomey', True, 50),\n",
       " (456, False, 'Mr_Maurice_OConnor', False, 17),\n",
       " (457, True, 'Mr_Harry_Anderson', False, 48),\n",
       " (458, False, 'Mr_William_Morley', False, 34),\n",
       " (459, False, 'Mr_Arthur_H_Gee', False, 47),\n",
       " (460, False, 'Mr_Jacob_Christian_Milling', False, 48),\n",
       " (461, False, 'Mr_Simon_Maisner', False, 34),\n",
       " (462, False, 'Mr_Manuel_Estanslas_Goncalves', False, 38),\n",
       " (463, False, 'Mr_William_Campbell', False, 21),\n",
       " (464, False, 'Mr_John_Montgomery_Smart', False, 56),\n",
       " (465, False, 'Mr_James_Scanlan', False, 22),\n",
       " (466, True, 'Miss_Helene_Barbara_Baclini', True, 1),\n",
       " (467, False, 'Mr_Arthur_Keefe', False, 39),\n",
       " (468, False, 'Mr_Luka_Cacic', False, 38),\n",
       " (469, True, 'Mrs_Edwy_Arthur_(Ada_Mary_Worth)_West', True, 33),\n",
       " (470, True, 'Mrs_Amin_S_(Marie_Marthe_Thuillard)_Jerwan', True, 23),\n",
       " (471, False, 'Miss_Ida_Sofia_Strandberg', True, 22),\n",
       " (472, False, 'Mr_George_Quincy_Clifford', False, 40),\n",
       " (473, False, 'Mr_Peter_Henry_Renouf', False, 34),\n",
       " (474, False, 'Mr_Lewis_Richard_Braund', False, 29),\n",
       " (475, False, 'Mr_Nils_August_Karlsson', False, 22),\n",
       " (476, True, 'Miss_Hildur_E_Hirvonen', True, 2),\n",
       " (477, False, 'Master_Harold_Victor_Goodwin', False, 9),\n",
       " (478, False, 'Mr_Anthony_Wood_Frost', False, 37),\n",
       " (479, False, 'Mr_Richard_Henry_Rouse', False, 50),\n",
       " (480, True, 'Mrs_(Hedwig)_Turkula', True, 63),\n",
       " (481, True, 'Mr_Dickinson_H_Bishop', False, 25),\n",
       " (482, False, 'Miss_Jeannie_Lefebre', True, 8),\n",
       " (483, True, 'Mrs_Frederick_Maxfield_(Jane_Anne_Forby)_Hoyt', True, 35),\n",
       " (484, False, 'Mr_Edward_Austin_Kent', False, 58),\n",
       " (485, False, 'Mr_Francis_William_Somerton', False, 30),\n",
       " (486, True, 'Master_Eden_Leslie_Coutts', False, 9),\n",
       " (487, False, 'Mr_Konrad_Mathias_Reiersen_Hagland', False, 19),\n",
       " (488, False, 'Mr_Einar_Windelov', False, 21),\n",
       " (489, False, 'Mr_Harry_Markland_Molson', False, 55),\n",
       " (490, False, 'Mr_Ramon_Artagaveytia', False, 71),\n",
       " (491, False, 'Mr_Edward_Roland_Stanley', False, 21),\n",
       " (492, False, 'Mr_Gerious_Yousseff', False, 26),\n",
       " (493, True, 'Miss_Elizabeth_Mussey_Eustis', True, 54),\n",
       " (494, False, 'Mr_Frederick_William_Shellard', False, 55),\n",
       " (495, False, 'Mrs_Hudson_J_C_(Bessie_Waldo_Daniels)_Allison', True, 25),\n",
       " (496, False, 'Mr_Olof_Svensson', False, 24),\n",
       " (497, False, 'Mr_Petar_Calic', False, 17),\n",
       " (498, False, 'Miss_Mary_Canavan', True, 21),\n",
       " (499, False, 'Miss_Bridget_Mary_OSullivan', True, 21),\n",
       " (500, False, 'Miss_Kristina_Sofia_Laitinen', True, 37),\n",
       " (501, True, 'Miss_Roberta_Maioni', True, 16),\n",
       " (502, False, 'Mr_Victor_de_Satode_Penasco_y_Castellana', False, 18),\n",
       " (503, True, 'Mrs_Frederick_Charles_(Jane_Richards)_Quick', True, 33),\n",
       " (504, True, 'Mr_George_Bradley', False, 37),\n",
       " (505, False, 'Mr_Henry_Margido_Olsen', False, 28),\n",
       " (506, True, 'Mr_Fang_Lang', False, 26),\n",
       " (507, True, 'Mr_Eugene_Patrick_Daly', False, 29),\n",
       " (508, False, 'Mr_James_Webber', False, 66),\n",
       " (509, True, 'Mr_James_Robert_McGough', False, 36),\n",
       " (510, True, 'Mrs_Martin_(Elizabeth_L_Barrett)_Rothschild', True, 54),\n",
       " (511, False, 'Mr_Satio_Coleff', False, 24),\n",
       " (512, False, 'Mr_William_Anderson_Walker', False, 47),\n",
       " (513, True, 'Mrs_(Amelia_Milley)_Lemore', True, 34),\n",
       " (514, False, 'Mr_Patrick_Ryan', False, 30),\n",
       " (515, True, 'Mrs_William_A_(Florence_Agnes_Hughes)_Angle', True, 36),\n",
       " (516, False, 'Mr_Stefo_Pavlovic', False, 32),\n",
       " (517, True, 'Miss_Anne_Perreault', True, 30),\n",
       " (518, False, 'Mr_Janko_Vovk', False, 22),\n",
       " (519, False, 'Mr_Sarkis_Lahoud', False, 35),\n",
       " (520, True, 'Mrs_Louis_Albert_(Ida_Sophia_Fischer)_Hippach', True, 44),\n",
       " (521, False, 'Mr_Fared_Kassem', False, 18),\n",
       " (522, False, 'Mr_James_Farrell', False, 41),\n",
       " (523, True, 'Miss_Lucy_Ridsdale', True, 50),\n",
       " (524, False, 'Mr_John_Farthing', False, 49),\n",
       " (525, False, 'Mr_Johan_Werner_Salonen', False, 39),\n",
       " (526, False, 'Mr_Richard_George_Hocking', False, 23),\n",
       " (527, True, 'Miss_Phyllis_May_Quick', True, 2),\n",
       " (528, False, 'Mr_Nakli_Toufik', False, 17),\n",
       " (529, False, 'Mr_Joseph_Jr_Elias', False, 17),\n",
       " (530, True, 'Mrs_Catherine_(Catherine_Rizk)_Peter', True, 24),\n",
       " (531, False, 'Miss_Marija_Cacic', True, 30),\n",
       " (532, True, 'Miss_Eva_Miriam_Hart', True, 7),\n",
       " (533, False, 'Major_Archibald_Willingham_Butt', False, 45),\n",
       " (534, True, 'Miss_Bertha_LeRoy', True, 30),\n",
       " (535, False, 'Mr_Samuel_Beard_Risien', False, 69),\n",
       " (536, True, 'Miss_Hedwig_Margaritha_Frolicher', True, 22),\n",
       " (537, True, 'Miss_Harriet_R_Crosby', True, 36),\n",
       " (538, False, 'Miss_Ingeborg_Constanzia_Andersson', True, 9),\n",
       " (539, False, 'Miss_Sigrid_Elisabeth_Andersson', True, 11),\n",
       " (540, True, 'Mr_Edward_Beane', False, 32),\n",
       " (541, False, 'Mr_Walter_Donald_Douglas', False, 50),\n",
       " (542, False, 'Mr_Arthur_Ernest_Nicholson', False, 64),\n",
       " (543, True, 'Mrs_Edward_(Ethel_Clarke)_Beane', True, 19),\n",
       " (544, True, 'Mr_Julian_Padro_y_Manent', False, 27),\n",
       " (545, False, 'Mr_Frank_John_Goldsmith', False, 33),\n",
       " (546, True, 'Master_John_Morgan_Jr_Davies', False, 8),\n",
       " (547, True, 'Mr_John_Borland_Jr_Thayer', False, 17),\n",
       " (548, False, 'Mr_Percival_James_R_Sharp', False, 27),\n",
       " (549, False, 'Mr_Timothy_OBrien', False, 21),\n",
       " (550, True, 'Mr_Fahim_Leeni', False, 22),\n",
       " (551, True, 'Miss_Velin_Ohman', True, 22),\n",
       " (552, False, 'Mr_George_Wright', False, 62),\n",
       " (553, True, 'Lady_(Lucille_Christiana_Sutherland)Duff_Gordon', True, 48),\n",
       " (554, False, 'Mr_Victor_Robbins', False, 45),\n",
       " (555, True, 'Mrs_Emil_(Tillie_Mandelbaum)_Taussig', True, 39),\n",
       " (556, True, 'Mrs_Guillaume_Joseph_(Emma)_de_Messemaeker', True, 36),\n",
       " (557, False, 'Mr_Thomas_Rowan_Morrow', False, 30),\n",
       " (558, False, 'Mr_Husein_Sivic', False, 40),\n",
       " (559, False, 'Mr_Robert_Douglas_Norman', False, 28),\n",
       " (560, False, 'Mr_John_Simmons', False, 40),\n",
       " (561, False, 'Miss_(Marion_Ogden)_Meanwell', True, 62),\n",
       " (562, False, 'Mr_Alfred_J_Davies', False, 24),\n",
       " (563, False, 'Mr_Ilia_Stoytcheff', False, 19),\n",
       " (564, False, 'Mrs_Nils_(Alma_Cornelia_Berglund)_Palsson', True, 29),\n",
       " (565, False, 'Mr_Tannous_Doharr', False, 28),\n",
       " (566, True, 'Mr_Carl_Jonsson', False, 32),\n",
       " (567, True, 'Mr_George_Harris', False, 62),\n",
       " (568, True, 'Mrs_Edward_Dale_(Charlotte_Lamson)_Appleton', True, 53),\n",
       " (569, True, 'Mr_John_Irwin_Flynn', False, 36),\n",
       " (570, True, 'Miss_Mary_Kelly', True, 22),\n",
       " (571, False, 'Mr_Alfred_George_John_Rush', False, 16),\n",
       " (572, False, 'Mr_George_Patchett', False, 19),\n",
       " (573, True, 'Miss_Ethel_Garside', True, 34),\n",
       " (574, True, 'Mrs_William_Baird_(Alice_Munger)_Silvey', True, 39),\n",
       " (575, False, 'Mrs_Joseph_(Maria_Elias)_Caram', True, 18),\n",
       " (576, True, 'Mr_Eiriik_Jussila', False, 32),\n",
       " (577, True, 'Miss_Julie_Rachel_Christy', True, 25),\n",
       " (578, True, 'Mrs_John_Borland_(Marian_Longstreth_Morris)_Thayer', True, 39),\n",
       " (579, False, 'Mr_William_James_Downton', False, 54),\n",
       " (580, False, 'Mr_John_Hugo_Ross', False, 36),\n",
       " (581, False, 'Mr_Uscher_Paulner', False, 16),\n",
       " (582, True, 'Miss_Ruth_Taussig', True, 18),\n",
       " (583, False, 'Mr_John_Denzil_Jarvis', False, 47),\n",
       " (584, True, 'Mr_Maxmillian_Frolicher-Stehli', False, 60),\n",
       " (585, False, 'Mr_Eliezer_Gilinski', False, 22),\n",
       " (586, False, 'Mr_Joseph_Murdlin', False, 22),\n",
       " (587, False, 'Mr_Matti_Rintamaki', False, 35),\n",
       " (588, True, 'Mrs_Walter_Bertram_(Martha_Eustis)_Stephenson', True, 52),\n",
       " (589, False, 'Mr_William_James_Elsbury', False, 47),\n",
       " (590, False, 'Miss_Mary_Bourke', True, 40),\n",
       " (591, False, 'Mr_John_Henry_Chapman', False, 37),\n",
       " (592, False, 'Mr_Jean_Baptiste_Van_Impe', False, 36),\n",
       " (593, True, 'Miss_Jessie_Wills_Leitch', True, 31),\n",
       " (594, False, 'Mr_Alfred_Johnson', False, 49),\n",
       " (595, False, 'Mr_Hanna_Boulos', False, 18),\n",
       " (596, True, 'Sir_Cosmo_Edmund_Duff_Gordon', False, 49),\n",
       " (597, True, 'Mrs_Sidney_Samuel_(Amy_Frances_Christy)_Jacobsohn', True, 24),\n",
       " (598, False, 'Mr_Petco_Slabenoff', False, 42),\n",
       " (599, False, 'Mr_Charles_H_Harrington', False, 37),\n",
       " (600, False, 'Mr_Ernst_William_Torber', False, 44),\n",
       " (601, True, 'Mr_Harry_Homer', False, 35),\n",
       " (602, False, 'Mr_Edvard_Bengtsson_Lindell', False, 36),\n",
       " (603, False, 'Mr_Milan_Karaic', False, 30),\n",
       " (604, True, 'Mr_Robert_Williams_Daniel', False, 27),\n",
       " (605, True, 'Mrs_Joseph_(Juliette_Marie_Louise_Lafargue)_Laroche', True, 22),\n",
       " (606, True, 'Miss_Elizabeth_W_Shutes', True, 40),\n",
       " (607,\n",
       "  False,\n",
       "  'Mrs_Anders_Johan_(Alfrida_Konstantia_Brogren)_Andersson',\n",
       "  True,\n",
       "  39),\n",
       " (608, False, 'Mr_Jose_Neto_Jardin', False, 21),\n",
       " (609, True, 'Miss_Margaret_Jane_Murphy', True, 18),\n",
       " (610, False, 'Mr_John_Horgan', False, 22),\n",
       " (611, False, 'Mr_William_Alfred_Brocklebank', False, 35),\n",
       " (612, True, 'Miss_Alice_Herman', True, 24),\n",
       " (613, False, 'Mr_Ernst_Gilbert_Danbom', False, 34),\n",
       " (614, False, 'Mrs_William_Arthur_(Cordelia_K_Stanlick)_Lobb', True, 26),\n",
       " (615, True, 'Miss_Marion_Louise_Becker', True, 4),\n",
       " (616, False, 'Mr_Lawrence_Gavey', False, 26),\n",
       " (617, False, 'Mr_Antoni_Yasbeck', False, 27),\n",
       " (618, True, 'Mr_Edwin_Nelson_Jr_Kimball', False, 42),\n",
       " (619, True, 'Mr_Sahid_Nakid', False, 20),\n",
       " (620, False, 'Mr_Henry_Damsgaard_Hansen', False, 21),\n",
       " (621, False, 'Mr_David_John_Bowen', False, 21),\n",
       " (622, False, 'Mr_Frederick_Sutton', False, 61),\n",
       " (623, False, 'Rev_Charles_Leonard_Kirkland', False, 57),\n",
       " (624, True, 'Miss_Gretchen_Fiske_Longley', True, 21),\n",
       " (625, False, 'Mr_Guentcho_Bostandyeff', False, 26),\n",
       " (626, False, 'Mr_Patrick_D_OConnell', False, 18),\n",
       " (627, True, 'Mr_Algernon_Henry_Wilson_Barkworth', False, 80),\n",
       " (628, False, 'Mr_Johan_Svensson_Lundahl', False, 51),\n",
       " (629, True, 'Dr_Max_Stahelin-Maeglin', False, 32),\n",
       " (630, False, 'Mr_William_Henry_Marsh_Parr', False, 30),\n",
       " (631, False, 'Miss_Mabel_Skoog', True, 9),\n",
       " (632, True, 'Miss_Mary_Davis', True, 28),\n",
       " (633, False, 'Mr_Antti_Gustaf_Leinonen', False, 32),\n",
       " (634, False, 'Mr_Harvey_Collyer', False, 31),\n",
       " (635, False, 'Mrs_Juha_(Maria_Emilia_Ojala)_Panula', True, 41),\n",
       " (636, False, 'Mr_Percival_Thorneycroft', False, 37),\n",
       " (637, False, 'Mr_Hans_Peder_Jensen', False, 20),\n",
       " (638, True, 'Mlle_Emma_Sagesser', True, 24),\n",
       " (639, False, 'Miss_Margit_Elizabeth_Skoog', True, 2),\n",
       " (640, True, 'Mr_Choong_Foo', False, 32),\n",
       " (641, True, 'Miss_Eugenie_Baclini', True, 1),\n",
       " (642, True, 'Mr_Henry_Sleeper_Harper', False, 48),\n",
       " (643, False, 'Mr_Liudevit_Cor', False, 19),\n",
       " (644, True, 'Col_Oberst_Alfons_Simonius-Blumer', False, 56),\n",
       " (645, False, 'Mr_Edward_Willey', False, 21),\n",
       " (646, True, 'Miss_Amy_Zillah_Elsie_Stanley', True, 23),\n",
       " (647, False, 'Mr_Mito_Mitkoff', False, 23),\n",
       " (648, True, 'Miss_Elsie_Doling', True, 18),\n",
       " (649, False, 'Mr_Johannes_Halvorsen_Kalvik', False, 21),\n",
       " (650, True, 'Miss_Hanora_OLeary', True, 16),\n",
       " (651, False, 'Miss_Hanora_Hegarty', True, 18),\n",
       " (652, False, 'Mr_Leonard_Mark_Hickman', False, 24),\n",
       " (653, False, 'Mr_Alexander_Radeff', False, 27),\n",
       " (654, False, 'Mrs_John_(Catherine)_Bourke', True, 32),\n",
       " (655, False, 'Mr_George_Floyd_Eitemiller', False, 23),\n",
       " (656, False, 'Mr_Arthur_Webster_Newell', False, 58),\n",
       " (657, True, 'Dr_Henry_William_Frauenthal', False, 50),\n",
       " (658, False, 'Mr_Mohamed_Badt', False, 40),\n",
       " (659, False, 'Mr_Edward_Pomeroy_Colley', False, 47),\n",
       " (660, False, 'Mr_Peju_Coleff', False, 36),\n",
       " (661, True, 'Mr_Eino_William_Lindqvist', False, 20),\n",
       " (662, False, 'Mr_Lewis_Hickman', False, 32),\n",
       " (663, False, 'Mr_Reginald_Fenton_Butler', False, 25),\n",
       " (664, False, 'Mr_Knud_Paust_Rommetvedt', False, 49),\n",
       " (665, False, 'Mr_Jacob_Cook', False, 43),\n",
       " (666, True, 'Mrs_Elmer_Zebley_(Juliet_Cummins_Wright)_Taylor', True, 48),\n",
       " (667,\n",
       "  True,\n",
       "  'Mrs_Thomas_William_Solomon_(Elizabeth_Catherine_Ford)_Brown',\n",
       "  True,\n",
       "  40),\n",
       " (668, False, 'Mr_Thornton_Davidson', False, 31),\n",
       " (669, False, 'Mr_Henry_Michael_Mitchell', False, 70),\n",
       " (670, True, 'Mr_Charles_Wilhelms', False, 31),\n",
       " (671, False, 'Mr_Ennis_Hastings_Watson', False, 19),\n",
       " (672, False, 'Mr_Gustaf_Hjalmar_Edvardsson', False, 18),\n",
       " (673, False, 'Mr_Frederick_Charles_Sawyer', False, 25),\n",
       " (674, True, 'Miss_Anna_Sofia_Turja', True, 18),\n",
       " (675, False, 'Mrs_Frederick_(Augusta_Tyler)_Goodwin', True, 43),\n",
       " (676, True, 'Mr_Thomas_Drake_Martinez_Cardeza', False, 36),\n",
       " (677, False, 'Miss_Katie_Peters', True, 28),\n",
       " (678, True, 'Mr_Hammad_Hassab', False, 27),\n",
       " (679, False, 'Mr_Thor_Anderson_Olsvigen', False, 20),\n",
       " (680, False, 'Mr_Charles_Edward_Goodwin', False, 14),\n",
       " (681, False, 'Mr_Thomas_William_Solomon_Brown', False, 60),\n",
       " (682, False, 'Mr_Joseph_Philippe_Lemercier_Laroche', False, 25),\n",
       " (683, False, 'Mr_Jaako_Arnold_Panula', False, 14),\n",
       " (684, False, 'Mr_Branko_Dakic', False, 19),\n",
       " (685, False, 'Mr_Eberhard_Thelander_Fischer', False, 18),\n",
       " (686, True, 'Miss_Georgette_Alexandra_Madill', True, 15),\n",
       " (687, True, 'Mr_Albert_Adrian_Dick', False, 31),\n",
       " (688, True, 'Miss_Manca_Karun', True, 4),\n",
       " (689, True, 'Mr_Ali_Lam', False, 37),\n",
       " (690, False, 'Mr_Khalil_Saad', False, 25),\n",
       " (691, False, 'Col_John_Weir', False, 60),\n",
       " (692, False, 'Mr_Charles_Henry_Chapman', False, 52),\n",
       " (693, False, 'Mr_James_Kelly', False, 44),\n",
       " (694, True, 'Miss_Katherine_Mullens', True, 19),\n",
       " (695, False, 'Mr_John_Borland_Thayer', False, 49),\n",
       " (696, False, 'Mr_Adolf_Mathias_Nicolai_Olsen_Humblen', False, 42),\n",
       " (697, True, 'Mrs_John_Jacob_(Madeleine_Talmadge_Force)_Astor', True, 18),\n",
       " (698, True, 'Mr_Spencer_Victor_Silverthorne', False, 35),\n",
       " (699, False, 'Miss_Saiide_Barbara', True, 18),\n",
       " (700, False, 'Mr_Martin_Gallagher', False, 25),\n",
       " (701, False, 'Mr_Henrik_Juul_Hansen', False, 26),\n",
       " (702, False, 'Mr_Henry_Samuel_Morley', False, 39),\n",
       " (703, True, 'Mrs_Florence_Kelly', True, 45),\n",
       " (704, True, 'Mr_Edward_Pennington_Calderhead', False, 42),\n",
       " (705, True, 'Miss_Alice_Cleaver', True, 22),\n",
       " (706, True, 'Master_Halim_Gonios_Moubarek', False, 4),\n",
       " (707, True, 'Mlle_Berthe_Antonine_Mayne', True, 24),\n",
       " (708, False, 'Mr_Herman_Klaber', False, 41),\n",
       " (709, True, 'Mr_Elmer_Zebley_Taylor', False, 48),\n",
       " (710, False, 'Mr_August_Viktor_Larsson', False, 29),\n",
       " (711, False, 'Mr_Samuel_Greenberg', False, 52),\n",
       " (712, False, 'Mr_Peter_Andreas_Lauritz_Andersen_Soholt', False, 19),\n",
       " (713, True, 'Miss_Caroline_Louise_Endres', True, 38),\n",
       " (714, True, 'Miss_Edwina_Celia_Troutt', True, 27),\n",
       " (715, False, 'Mr_Malkolm_Joackim_Johnson', False, 33),\n",
       " (716, True, 'Miss_Annie_Jessie_Harper', True, 6),\n",
       " (717, False, 'Mr_Svend_Lauritz_Jensen', False, 17),\n",
       " (718, False, 'Mr_William_Henry_Gillespie', False, 34),\n",
       " (719, False, 'Mr_Henry_Price_Hodges', False, 50),\n",
       " (720, True, 'Mr_Norman_Campbell_Chambers', False, 27),\n",
       " (721, False, 'Mr_Luka_Oreskovic', False, 20),\n",
       " (722, True, 'Mrs_Peter_Henry_(Lillian_Jefferys)_Renouf', True, 30),\n",
       " (723, True, 'Miss_Margareth_Mannion', True, 28),\n",
       " (724, False, 'Mr_Kurt_Arnold_Gottfrid_Bryhl', False, 25),\n",
       " (725, False, 'Miss_Pieta_Sofia_Ilmakangas', True, 25),\n",
       " (726, True, 'Miss_Elisabeth_Walton_Allen', True, 29),\n",
       " (727, False, 'Mr_Houssein_G_N_Hassan', False, 11),\n",
       " (728, False, 'Mr_Robert_J_Knight', False, 41),\n",
       " (729, False, 'Mr_William_John_Berriman', False, 23),\n",
       " (730, False, 'Mr_Moses_Aaron_Troupiansky', False, 23),\n",
       " (731, False, 'Mr_Leslie_Williams', False, 29),\n",
       " (732, False, 'Mrs_Edward_(Margaret_Ann_Watson)_Ford', True, 48),\n",
       " (733, True, 'Mr_Gustave_J_Lesurer', False, 35),\n",
       " (734, False, 'Mr_Kanio_Ivanoff', False, 20),\n",
       " (735, False, 'Mr_Minko_Nankoff', False, 32),\n",
       " (736, True, 'Mr_Walter_James_Hawksford', False, 45),\n",
       " (737, False, 'Mr_Tyrell_William_Cavendish', False, 36),\n",
       " (738, True, 'Miss_Susan_Parker_Ryerson', True, 21),\n",
       " (739, False, 'Mr_Neal_McNamee', False, 24),\n",
       " (740, True, 'Mr_Juho_Stranden', False, 31),\n",
       " (741, False, 'Capt_Edward_Gifford_Crosby', False, 70),\n",
       " (742, False, 'Mr_Rossmore_Edward_Abbott', False, 16),\n",
       " (743, True, 'Miss_Anna_Sinkkonen', True, 30),\n",
       " (744, False, 'Mr_Daniel_Warner_Marvin', False, 19),\n",
       " (745, False, 'Mr_Michael_Connaghton', False, 31),\n",
       " (746, True, 'Miss_Joan_Wells', True, 4),\n",
       " (747, True, 'Master_Meier_Moor', False, 6),\n",
       " (748, False, 'Mr_Johannes_Joseph_Vande_Velde', False, 33),\n",
       " (749, False, 'Mr_Lalio_Jonkoff', False, 23),\n",
       " (750, True, 'Mrs_Samuel_(Jane_Laver)_Herman', True, 48),\n",
       " (751, True, 'Master_Viljo_Hamalainen', False, 1),\n",
       " (752, False, 'Mr_August_Sigfrid_Carlsson', False, 28),\n",
       " (753, False, 'Mr_Percy_Andrew_Bailey', False, 18),\n",
       " (754, False, 'Mr_Thomas_Leonard_Theobald', False, 34),\n",
       " (755,\n",
       "  True,\n",
       "  'the_Countess_of_(Lucy_Noel_Martha_Dyer-Edwards)_Rothes',\n",
       "  True,\n",
       "  33),\n",
       " (756, False, 'Mr_John_Garfirth', False, 23),\n",
       " (757, False, 'Mr_Iisakki_Antino_Aijo_Nirva', False, 41),\n",
       " (758, True, 'Mr_Hanna_Assi_Barah', False, 20),\n",
       " (759, True, 'Mrs_William_Ernest_(Lucile_Polk)_Carter', True, 36),\n",
       " (760, False, 'Mr_Hans_Linus_Eklund', False, 16),\n",
       " (761, True, 'Mrs_John_C_(Anna_Andrews)_Hogeboom', True, 51),\n",
       " (762, False, 'Dr_Arthur_Jackson_Brewe', False, 46),\n",
       " (763, False, 'Miss_Mary_Mangan', True, 31),\n",
       " (764, False, 'Mr_Daniel_J_Moran', False, 28),\n",
       " (765, False, 'Mr_Daniel_Danielsen_Gronnestad', False, 32),\n",
       " (766, False, 'Mr_Rene_Aime_Lievens', False, 24),\n",
       " (767, False, 'Mr_Niels_Peder_Jensen', False, 48),\n",
       " (768, False, 'Mrs_(Mary)_Mack', True, 57),\n",
       " (769, False, 'Mr_Dibo_Elias', False, 29),\n",
       " (770, True, 'Mrs_Elizabeth_(Eliza_Needs)_Hocking', True, 54),\n",
       " (771, False, 'Mr_Pehr_Fabian_Oliver_Malkolm_Myhrman', False, 18),\n",
       " (772, False, 'Mr_Roger_Tobin', False, 20),\n",
       " (773, True, 'Miss_Virginia_Ethel_Emanuel', True, 5),\n",
       " (774, False, 'Mr_Thomas_J_Kilgannon', False, 22),\n",
       " (775, True, 'Mrs_Edward_Scott_(Elisabeth_Walton_McMillan)_Robert', True, 43),\n",
       " (776, True, 'Miss_Banoura_Ayoub', True, 13),\n",
       " (777, True, 'Mrs_Albert_Adrian_(Vera_Gillespie)_Dick', True, 17),\n",
       " (778, False, 'Mr_Milton_Clyde_Long', False, 29),\n",
       " (779, False, 'Mr_Andrew_G_Johnston', False, 35),\n",
       " (780, False, 'Mr_William_Ali', False, 25),\n",
       " (781, False, 'Mr_Abraham_(David_Lishin)_Harmer', False, 25),\n",
       " (782, True, 'Miss_Anna_Sofia_Sjoblom', True, 18),\n",
       " (783, False, 'Master_George_Hugh_Rice', False, 8),\n",
       " (784, True, 'Master_Bertram_Vere_Dean', False, 1),\n",
       " (785, False, 'Mr_Benjamin_Guggenheim', False, 46),\n",
       " (786, False, 'Mr_Andrew_Keane', False, 20),\n",
       " (787, False, 'Mr_Alfred_Gaskell', False, 16),\n",
       " (788, False, 'Miss_Stella_Anna_Sage', True, 21),\n",
       " (789, False, 'Mr_William_Fisher_Hoyt', False, 43),\n",
       " (790, False, 'Mr_Ristiu_Dantcheff', False, 25),\n",
       " (791, False, 'Mr_Richard_Otter', False, 39),\n",
       " (792, True, 'Dr_Alice_(Farnham)_Leader', True, 49),\n",
       " (793, True, 'Mrs_Mara_Osman', True, 31),\n",
       " (794, False, 'Mr_Yousseff_Ibrahim_Shawah', False, 30),\n",
       " (795, False, 'Mrs_Jean_Baptiste_(Rosalie_Paula_Govaert)_Van_Impe', True, 30),\n",
       " (796, False, 'Mr_Martin_Ponesell', False, 34),\n",
       " (797, True, 'Mrs_Harvey_(Charlotte_Annie_Tate)_Collyer', True, 31),\n",
       " (798, True, 'Master_William_Thornton_II_Carter', False, 11),\n",
       " (799, True, 'Master_Assad_Alexander_Thomas', False, 0),\n",
       " (800, True, 'Mr_Oskar_Arvid_Hedman', False, 27),\n",
       " (801, False, 'Mr_Karl_Johan_Johansson', False, 31),\n",
       " (802, False, 'Mr_Thomas_Jr_Andrews', False, 39),\n",
       " (803, False, 'Miss_Ellen_Natalia_Pettersson', True, 18),\n",
       " (804, False, 'Mr_August_Meyer', False, 39),\n",
       " (805, True, 'Mrs_Norman_Campbell_(Bertha_Griggs)_Chambers', True, 33),\n",
       " (806, False, 'Mr_William_Alexander', False, 26),\n",
       " (807, False, 'Mr_James_Lester', False, 39),\n",
       " (808, False, 'Mr_Richard_James_Slemen', False, 35),\n",
       " (809, False, 'Miss_Ebba_Iris_Alfrida_Andersson', True, 6),\n",
       " (810, False, 'Mr_Ernest_Portage_Tomlin', False, 31),\n",
       " (811, False, 'Mr_Richard_Fry', False, 39),\n",
       " (812, False, 'Miss_Wendla_Maria_Heininen', True, 23),\n",
       " (813, False, 'Mr_Albert_Mallet', False, 31),\n",
       " (814, False, 'Mr_John_Fredrik_Alexander_Holm', False, 43),\n",
       " (815, False, 'Master_Karl_Thorsten_Skoog', False, 10),\n",
       " (816, True, 'Mrs_Charles_Melville_(Clara_Jennings_Gregg)_Hays', True, 52),\n",
       " (817, True, 'Mr_Nikola_Lulic', False, 27),\n",
       " (818, False, 'Jonkheer_John_George_Reuchlin', False, 38),\n",
       " (819, True, 'Mrs_(Beila)_Moor', True, 27),\n",
       " (820, False, 'Master_Urho_Abraham_Panula', False, 2),\n",
       " (821, False, 'Mr_John_Flynn', False, 36),\n",
       " (822, False, 'Mr_Len_Lam', False, 23),\n",
       " (823, True, 'Master_Andre_Mallet', False, 1),\n",
       " (824, True, 'Mr_Thomas_Joseph_McCormack', False, 19),\n",
       " (825, True, 'Mrs_George_Nelson_(Martha_Evelyn)_Stone', True, 62),\n",
       " (826, True, 'Mrs_Antoni_(Selini_Alexander)_Yasbeck', True, 15),\n",
       " (827, True, 'Master_George_Sibley_Richards', False, 1),\n",
       " (828, False, 'Mr_Amin_Saad', False, 30),\n",
       " (829, False, 'Mr_Albert_Augustsson', False, 23),\n",
       " (830, False, 'Mr_Owen_George_Allum', False, 18),\n",
       " (831, True, 'Miss_Sara_Rebecca_Compton', True, 39),\n",
       " (832, False, 'Mr_Jakob_Pasic', False, 21),\n",
       " (833, False, 'Mr_Maurice_Sirota', False, 20),\n",
       " (834, True, 'Mr_Chang_Chip', False, 32),\n",
       " (835, True, 'Mr_Pierre_Marechal', False, 29),\n",
       " (836, False, 'Mr_Ilmari_Rudolf_Alhomaki', False, 20),\n",
       " (837, False, 'Mr_Thomas_Charles_Mudd', False, 16),\n",
       " (838, True, 'Miss_Augusta_Serepeca', True, 30),\n",
       " (839, False, 'Mr_Peter_L_Lemberopolous', False, 35),\n",
       " (840, False, 'Mr_Jeso_Culumovic', False, 17),\n",
       " (841, False, 'Mr_Anthony_Abbing', False, 42),\n",
       " (842, False, 'Mr_Douglas_Bullen_Sage', False, 18),\n",
       " (843, False, 'Mr_Marin_Markoff', False, 35),\n",
       " (844, False, 'Rev_John_Harper', False, 28),\n",
       " (845, True, 'Mrs_Samuel_L_(Edwiga_Grabowska)_Goldenberg', True, 40),\n",
       " (846, False, 'Master_Sigvard_Harald_Elias_Andersson', False, 4),\n",
       " (847, False, 'Mr_Johan_Svensson', False, 74),\n",
       " (848, False, 'Miss_Nourelain_Boulos', True, 9),\n",
       " (849, True, 'Miss_Mary_Conover_Lines', True, 16),\n",
       " (850, False, 'Mrs_Ernest_Courtenay_(Lilian_Hughes)_Carter', True, 44),\n",
       " (851, True, 'Mrs_Sam_(Leah_Rosen)_Aks', True, 18),\n",
       " (852, True, 'Mrs_George_Dennick_(Mary_Hitchcock)_Wick', True, 45),\n",
       " (853, True, 'Mr_Peter_Denis_Daly', False, 51),\n",
       " (854, True, 'Mrs_Solomon_(Latifa_Qurban)_Baclini', True, 24),\n",
       " (855, False, 'Mr_Raihed_Razi', False, 30),\n",
       " (856, False, 'Mr_Claus_Peter_Hansen', False, 41),\n",
       " (857, False, 'Mr_Frederick_Edward_Giles', False, 21),\n",
       " (858, True, 'Mrs_Frederick_Joel_(Margaret_Welles_Barron)_Swift', True, 48),\n",
       " (859, False, 'Miss_Dorothy_Edith_Sage', True, 14),\n",
       " (860, False, 'Mr_John_William_Gill', False, 24),\n",
       " (861, True, 'Mrs_(Karolina)_Bystrom', True, 42),\n",
       " (862, True, 'Miss_Asuncion_Duran_y_More', True, 27),\n",
       " (863, False, 'Mr_Washington_Augustus_II_Roebling', False, 31),\n",
       " (864, False, 'Mr_Philemon_van_Melkebeke', False, 23),\n",
       " (865, True, 'Master_Harold_Theodor_Johnson', False, 4),\n",
       " (866, False, 'Mr_Cerin_Balkic', False, 26),\n",
       " (867, True, 'Mrs_Richard_Leonard_(Sallie_Monypeny)_Beckwith', True, 47),\n",
       " (868, False, 'Mr_Frans_Olof_Carlsson', False, 33),\n",
       " (869, False, 'Mr_Victor_Vander_Cruyssen', False, 47),\n",
       " (870, True, 'Mrs_Samuel_(Hannah_Wizosky)_Abelson', True, 28),\n",
       " (871, True, 'Miss_Adele_Kiamie_Najib', True, 15),\n",
       " (872, False, 'Mr_Alfred_Ossian_Gustafsson', False, 20),\n",
       " (873, False, 'Mr_Nedelio_Petroff', False, 19),\n",
       " (874, False, 'Mr_Kristo_Laleff', False, 23),\n",
       " (875, True, 'Mrs_Thomas_Jr_(Lily_Alexenia_Wilson)_Potter', True, 56),\n",
       " (876, True, 'Mrs_William_(Imanita_Parrish_Hall)_Shelley', True, 25),\n",
       " (877, False, 'Mr_Johann_Markun', False, 33),\n",
       " (878, False, 'Miss_Gerda_Ulrika_Dahlberg', True, 22),\n",
       " (879, False, 'Mr_Frederick_James_Banfield', False, 28),\n",
       " (880, False, 'Mr_Henry_Jr_Sutehall', False, 25),\n",
       " (881, False, 'Mrs_William_(Margaret_Norton)_Rice', True, 39),\n",
       " (882, False, 'Rev_Juozas_Montvila', False, 27),\n",
       " (883, True, 'Miss_Margaret_Edith_Graham', True, 19),\n",
       " (884, False, 'Miss_Catherine_Helen_Johnston', True, 7),\n",
       " (885, True, 'Mr_Karl_Howell_Behr', False, 26),\n",
       " (886, False, 'Mr_Patrick_Dooley', False, 32)]"
      ]
     },
     "execution_count": 165,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "curs.fetchall()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 163,
   "metadata": {},
   "outputs": [],
   "source": [
    "features= [\"Survived\",\"Name\",\"Age\",\"Sex\"]\n",
    "for i in range(len(ship)):\n",
    "   curs.execute(f\"INSERT INTO titanic_table VALUES({i}, '{ship['Survived'][i]}', '{ship['Name'][i]}','{ship['Sex'][i]}',{ship['Age'][i]} )\")\n",
    "conn.commit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 157,
   "metadata": {},
   "outputs": [],
   "source": [
    "curs.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 158,
   "metadata": {},
   "outputs": [],
   "source": [
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
